[project]
name = "dirbypy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "json-log-formatter>=1.1.1",
    "pytest>=8.4.2",
]
